#ifndef FARMCPUFLAG_HPP
#define FARMCPUFLAG_HPP

#include <cstdint>

namespace FARMCPU
{

enum FARMCPU_ERROR_FLAG : int32_t
{
    FARMCPUPRE_ERROR_SUCCESS = 0,

    FARMCPUPRE_ERROR_SAMPLE_FILTER_SET_FILTER_NULL,
    FARMCPUPRE_ERROR_SAMPLE_FILTER_SET_FILTER_EMPTY,
    FARMCPUPRE_ERROR_SAMPLE_FILTER_FILTER_MARKER_FAIL,

    FARMCPUPRE_ERROR_UTIL_CALC_MAF_X_UNVALID,
    FARMCPUPRE_ERROR_UTIL_CALC_MAF_X_EMPTY,
    FARMCPUPRE_ERROR_UTIL_SORT_VEC_N_UNEQUAL,
    FARMCPUPRE_ERROR_UTIL_SORT_VEC_EMPTY,

    FARMCPUPRE_ERROR_LM_UNINIT,
    FARMCPUPRE_ERROR_LM_M_NUM_UNEQUAL,
    FARMCPUPRE_ERROR_LM_Y_VEC_NO_COLVEC,
    FARMCPUPRE_ERROR_LM_X_VEC_NO_COLVEC,
    FARMCPUPRE_ERROR_LM_Y_VEC_EMPTY,
    FARMCPUPRE_ERROR_LM_W_MAT_EMPTY,
    FARMCPUPRE_ERROR_LM_X_VEC_EMPTY,
    FARMCPUPRE_ERROR_LM_SQRTBETAX_ZERO,

    FARMCPUPRE_ERROR_LDREMOVE_CORRELATION,
    FARMCPUPRE_ERROR_LDREMOVE_N_GENO_ZERO,
    FARMCPUPRE_ERROR_LDREMOVE_M_NUM_UNEQUAL,
    FARMCPUPRE_ERROR_LDREMOVE_M_GENO_ZERO,
    FARMCPUPRE_ERROR_LDREMOVE_N_ORDER_EMPTY,
    FARMCPUPRE_ERROR_LDREMOVE_GENO_READ_ERROR,

    FARMCPUPRE_ERROR_BICSELECTION_M_NUM_UNEQUAL,
    FARMCPUPRE_ERROR_BICSELECTION_N_GENO_ZERO,
    FARMCPUPRE_ERROR_BICSELECTION_N_ORDER_EMPTY,
    FARMCPUPRE_ERROR_BICSELECTION_PST_STRUCT_NULL,
    FARMCPUPRE_ERROR_BICSELECTION_STRUCT_UNINIT,
    FARMCPUPRE_ERROR_BICSELECTION_INIT_Y_IS_NOT_COLVEC,
    FARMCPUPRE_ERROR_BICSELECTION_INIT_Y_EMPTY,
    FARMCPUPRE_ERROR_BICSELECTION_INIT_W_UNVALID,
    FARMCPUPRE_ERROR_BICSELECTION_INIT_M_UNEQUAL,
    FARMCPUPRE_ERROR_BICSELECTION_GENO_READ_ERROR,
};

};

#endif